name: Release Package

on:
    workflow_dispatch:
        description: This will increment version and publish package.
        inputs:
            type:
                description: '"major", "minor" or "patch"'
                required: true
                default: missing
env:
    NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    ACCESS_REPOS: ${{ secrets.ACCESS_REPOS }}
    WRITE_PACKAGES: ${{ secrets.WRITE_PACKAGES }}
jobs:
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: 12
    #         - run: npm ci
    #         - run: npm test
    publish:
        # needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ env.ACCESS_REPOS }}
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
            - run: git config user.email developers@rnwl.co
            - run: git config user.name "package-api-mocks/release-package"
            - run: npm ci
            - id: version
              run: echo "::set-output name=version::$(npm version ${{ github.event.inputs.type }})"
            - run: git push
            - run: git push origin ${{ steps.version.outputs.version }}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ env.WRITE_PACKAGES }}
            # todo - uses: ./.github/actions/create-github-release
